name: Npm Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  Npm-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install Deps
        run: yarn install

      - name: publish with latest tag
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
